# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_conf_Dialog(object):
    def setupUi(self, conf_Dialog):
        conf_Dialog.setObjectName("conf_Dialog")
        conf_Dialog.resize(392, 423)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        conf_Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(conf_Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 5, 10, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(conf_Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(conf_Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.user = QtWidgets.QLineEdit(conf_Dialog)
        self.user.setObjectName("user")
        self.gridLayout.addWidget(self.user, 2, 1, 1, 1)
        self.port = QtWidgets.QLineEdit(conf_Dialog)
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 1, 3, 1, 1)
        self.password = QtWidgets.QLineEdit(conf_Dialog)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(conf_Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(conf_Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.db_address = QtWidgets.QLineEdit(conf_Dialog)
        self.db_address.setObjectName("db_address")
        self.gridLayout.addWidget(self.db_address, 1, 1, 1, 1)
        self.testconnect_pushButton = QtWidgets.QPushButton(conf_Dialog)
        self.testconnect_pushButton.setObjectName("testconnect_pushButton")
        self.gridLayout.addWidget(self.testconnect_pushButton, 3, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(conf_Dialog)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.relation_tableView = QtWidgets.QTableView(self.groupBox)
        self.relation_tableView.setShowGrid(True)
        self.relation_tableView.setObjectName("relation_tableView")
        self.verticalLayout_4.addWidget(self.relation_tableView)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(conf_Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(conf_Dialog)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.add_relation_pushButton = QtWidgets.QPushButton(conf_Dialog)
        self.add_relation_pushButton.setObjectName("add_relation_pushButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.add_relation_pushButton)
        self.show_name = QtWidgets.QLineEdit(conf_Dialog)
        self.show_name.setObjectName("show_name")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.show_name)
        self.table_name = QtWidgets.QLineEdit(conf_Dialog)
        self.table_name.setObjectName("table_name")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.table_name)
        self.del_relation_pushButton = QtWidgets.QPushButton(conf_Dialog)
        self.del_relation_pushButton.setObjectName("del_relation_pushButton")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.del_relation_pushButton)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout_3.setStretch(0, 7)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(conf_Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(conf_Dialog)
        self.buttonBox.accepted.connect(conf_Dialog.accept)
        self.buttonBox.rejected.connect(conf_Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(conf_Dialog)

    def retranslateUi(self, conf_Dialog):
        _translate = QtCore.QCoreApplication.translate
        conf_Dialog.setWindowTitle(_translate("conf_Dialog", "设置"))
        self.label_6.setText(_translate("conf_Dialog", "端口:"))
        self.label.setText(_translate("conf_Dialog", "数据库地址:"))
        self.label_2.setText(_translate("conf_Dialog", "账号:"))
        self.label_5.setText(_translate("conf_Dialog", "密码:"))
        self.testconnect_pushButton.setText(_translate("conf_Dialog", "测试链接"))
        self.groupBox.setTitle(_translate("conf_Dialog", "显示名称和对应表"))
        self.label_3.setText(_translate("conf_Dialog", "显示名称:"))
        self.label_4.setText(_translate("conf_Dialog", "对应表名:"))
        self.add_relation_pushButton.setText(_translate("conf_Dialog", "添加对应关系"))
        self.del_relation_pushButton.setText(_translate("conf_Dialog", "删除选中项"))

