# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'execl_tool.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(863, 637)
        MainWindow.setMinimumSize(QtCore.QSize(863, 637))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.main_widget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 740, 69))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_6.addWidget(self.scrollArea_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.search_pushButton = QtWidgets.QPushButton(self.main_widget)
        self.search_pushButton.setObjectName("search_pushButton")
        self.verticalLayout_3.addWidget(self.search_pushButton)
        self.clear_pushButton = QtWidgets.QPushButton(self.main_widget)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.verticalLayout_3.addWidget(self.clear_pushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.setStretch(0, 2)
        self.verticalLayout_9.addWidget(self.main_widget)
        self.add_widget = QtWidgets.QWidget(self.centralwidget)
        self.add_widget.setObjectName("add_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.add_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(self.add_widget)
        self.textBrowser.setStyleSheet("border:1px solid gray;\n"
"        border-radius:10px;\n"
"        padding:2px 4px;")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.add_widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_11.addWidget(self.label)
        self.table_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.table_comboBox.setObjectName("table_comboBox")
        self.horizontalLayout_11.addWidget(self.table_comboBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.selectTable_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.selectTable_pushButton.setObjectName("selectTable_pushButton")
        self.verticalLayout_8.addWidget(self.selectTable_pushButton)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.add_widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.add_widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.import_pushButton = QtWidgets.QPushButton(self.add_widget)
        self.import_pushButton.setObjectName("import_pushButton")
        self.horizontalLayout_7.addWidget(self.import_pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.add_widget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_9.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_9.addWidget(self.radioButton)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.export_pushButton = QtWidgets.QPushButton(self.add_widget)
        self.export_pushButton.setObjectName("export_pushButton")
        self.verticalLayout_6.addWidget(self.export_pushButton)
        self.verticalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.setStretch(0, 2)
        self.verticalLayout_5.setStretch(1, 3)
        self.verticalLayout_5.setStretch(2, 1)
        self.verticalLayout_5.setStretch(3, 3)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_9.addWidget(self.add_widget)
        self.verticalLayout_9.setStretch(1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionconfig = QtWidgets.QAction(MainWindow)
        self.actionconfig.setObjectName("actionconfig")
        self.actionversion = QtWidgets.QAction(MainWindow)
        self.actionversion.setObjectName("actionversion")
        self.menu.addAction(self.actionversion)
        self.menu_2.addAction(self.actionconfig)
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据库自适应查询工具"))
        self.search_pushButton.setText(_translate("MainWindow", "查询"))
        self.clear_pushButton.setText(_translate("MainWindow", "清空"))
        self.groupBox_2.setTitle(_translate("MainWindow", "数据表初始化"))
        self.label.setText(_translate("MainWindow", "需要查询的\n"
"用户数据表"))
        self.selectTable_pushButton.setText(_translate("MainWindow", "确定选择的表"))
        self.groupBox_3.setTitle(_translate("MainWindow", "数据操作"))
        self.pushButton.setText(_translate("MainWindow", "新增"))
        self.pushButton_2.setText(_translate("MainWindow", "修改"))
        self.pushButton_3.setText(_translate("MainWindow", "删除"))
        self.label_2.setText(_translate("MainWindow", "选择要导入的\n"
"execl:"))
        self.import_pushButton.setText(_translate("MainWindow", "导入......."))
        self.groupBox.setTitle(_translate("MainWindow", "导出选项"))
        self.radioButton_2.setText(_translate("MainWindow", "导出当前查询"))
        self.radioButton.setText(_translate("MainWindow", "导出全部"))
        self.export_pushButton.setText(_translate("MainWindow", "导出"))
        self.menu.setTitle(_translate("MainWindow", "软件信息"))
        self.menu_2.setTitle(_translate("MainWindow", "设置"))
        self.actionconfig.setText(_translate("MainWindow", "config"))
        self.actionversion.setText(_translate("MainWindow", "version"))

